<a href="https://colab.research.google.com/github/NGPGeeks/Acads/blob/main/VodafoneWorkshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Basics
# Nagarpalika
import numpy as np
print(np.__version__)

lst1 = [1,2,3,4]
array1 = np.array(lst1)

type(lst1)

type(array1)

lst2 = [10, 11, 12, 13]
array2 = np.array(lst2)

print(lst1+lst2)

print(array1 + array2)

np.random.seed(60)
x1 = np.random.randint(11, size=6)
x2 = np.random.randint(11, size=(5,4))
x3 = np.random.randint(11, size=(3,2,5))

print("One dimensional array")
print(x1)
print("Two dimensional array")
print(x2)
print("Three dimensional array")
print(x3)

print("Attributes of x3")
print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)

print("dtype:", x3.dtype)

print("itemsize", x3.itemsize, "bytes")
print("item nbytes", x3.nbytes, "bytes")



1.21.6
[1, 2, 3, 4, 10, 11, 12, 13]
[11 13 15 17]
One dimensional array
[ 1  6 10  3  8  9]
Two dimensional array
[[ 1  2  1  7]
 [10  8  5  2]
 [ 8  6  3  2]
 [ 5  0 10  3]
 [10  4  0  6]]
Three dimensional array
[[[10  6  9 10  5]
  [ 7  0 10  2  5]]

 [[ 8  7  9  4  0]
  [ 7  0  6  2  2]]

 [[ 0  8  1  6  8]
  [ 2  9 10  2  7]]]
Attributes of x3
x3 ndim 3
x3 shape (3, 2, 5)
x3 size 30
dtype: int64
itemsize 8 bytes
item nbytes 240 bytes


In [ ]:
lst1 = [1,2,3,4]
array1 = np.array(lst1)

In [ ]:
type(lst1)

list

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
lst2 = [10, 11, 12, 13]
array2 = np.array(lst2)

In [ ]:
print(lst1+lst2)

[1, 2, 3, 4, 10, 11, 12, 13]


In [ ]:
np.random.seed(60)
x1 = np.random.randint(11, size=6)
x2 = np.random.randint(11, size=(5,4))
x3 = np.random.randint(11, size=(3,2,5))

In [ ]:
print("One dimensional array")
print(x1)
print("Two dimensional array")
print(x2)
print("Three dimensional array")
print(x3)

One dimensional array
[ 1  6 10  3  8  9]
Two dimensional array
[[ 1  2  1  7]
 [10  8  5  2]
 [ 8  6  3  2]
 [ 5  0 10  3]
 [10  4  0  6]]
Three dimensional array
[[[10  6  9 10  5]
  [ 7  0 10  2  5]]

 [[ 8  7  9  4  0]
  [ 7  0  6  2  2]]

 [[ 0  8  1  6  8]
  [ 2  9 10  2  7]]]


In [ ]:
np.random.randint(10,100,15) #this creates an array of size 15 with random elements

array([85, 27, 17, 22, 65, 12, 44, 34, 20, 71, 36, 26, 49, 48, 27])

In [ ]:
mat = np.random.randint(10,100,15).reshape(5,3)
mat

array([[38, 87, 74],
       [19, 75, 74],
       [68, 70, 64],
       [12, 58, 18],
       [32, 52, 45]])

In [ ]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,1,2,3]])

In [ ]:
arr2.shape

(3, 4)

# Intersection of arrays

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

newarr = np.intersect1d(arr1,arr2)
print(newarr)

[]
